name: Package (Backmaster)

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
    tags:
      - "v*"
  release:
    types:
      - published

permissions:
  contents: read

jobs:
  test:
    uses: ./.github/workflows/ci.yml

  build-deb:
    needs: test
    uses: ./.github/workflows/deb.yml
